name: Build and Deploy

on: 
 repository_dispatch:
    types: [webhook-event]

env:
  webappname: WEB-TEC-SA-EAD-GITHUBACTIONS-DEV
  

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Get CR Details
      run: |
        echo "Title: ${{ github.event.client_payload.title }}"
        echo "PlatformResource: ${{ github.event.client_payload.PlatformResource }}"
        echo "Environment: ${{ github.event.client_payload.environment }}"
        
    - name: Update configs
      run: cp -r development.json ../src/assets/environments/development.json
      working-directory: EAD-Angular/configs

    - name: Use Node 18.x
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: npm install, build
      run: |
        npm install --force
        npm run build --prod
      working-directory: EAD-Angular
    
    # - name: List directory
    #   run: ls EAD-Angular
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: EAD-Angular/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Az CLI login
      uses: Azure/login@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: dist
    - name: ls
      run: ls /home/runner/work/EAD-Angular-UI/EAD-Angular-UI
        
    - name: Azure App Service Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.webappname }}
        package: /home/runner/work/EAD-Angular-UI/EAD-Angular-UI/
        startup-command: pm2 serve /home/site/wwwroot/ead/browser --no-daemon --spa
         
